### ISSUE TITLE
Reproducing paper results

### ISSUE THREAD

**Issue by aditya-jonn** [SarielMa/Increasing-Margin-Adversarial-Training#1]
Hi, thanks for sharing the code. Are there any changes (in default parameters) needed to reproduce the results in the paper?

**Comment by SarielMa** [comment]
Hi, thanks for reaching out. The default parameters in the code might be a little different from those in the paper, due to cleaning and rearranging the code. Please refer to the parameters in the paper for reproduction. Also, you can find our pre-trained model for reproduction. The link is provided on the introduction page.
